ProgettoBackend-S5-L5/Controllers/VerbaliController.cs
using Microsoft.AspNetCore.Mvc;
using ProgettoBackend_S5_L5.Services;
using ProgettoBackend_S5_L5.ViewModels;

namespace ProgettoBackend_S5_L5.Controllers
{
    public class VerbaliController : Controller
    {
        private readonly TrasgressoriService _trasgressoriService;
        private readonly VerbaliService _verbaliService;

        public VerbaliController(VerbaliService verbaliService, TrasgressoriService trasgressoriService)
        {
            _verbaliService = verbaliService;
            _trasgressoriService = trasgressoriService;
        }
        public async Task<IActionResult> Index()
        {
            var verbali = await _verbaliService.GetVerbaliAsync();

            return View(verbali);
        }

        [HttpGet("verbali/violazioni/{id:int}")]
        public async Task<IActionResult> Violazioni(int id)
        {
            var violazioni = await _verbaliService.GetViolazioniAsync(id);
            ViewData["idVerbale"] = id;

            return View(violazioni);
        }


        public async Task<IActionResult> AddViolaziones(int id)
        {
            var violazioni = await _verbaliService.GetAllViolazioniAsync();
            ViewData["idVerbale"] = id;
            return View(violazioni);
        }

        [HttpPost("verbali/violazioni/{id:int}")]
        public async Task<IActionResult> AddViolazione(int id, ViolazioneViewModel violazioneViewModel)
        {
            int idViolazione = violazioneViewModel.IdViolazione;
            int idVerbale = id;

            var nuovaViolazione = await _verbaliService.AddViolazioneAsync(idVerbale, idViolazione);

            return RedirectToAction("Index");
        }

        public async Task<IActionResult> AddVerbale()
        {
            ViewBag.Anagrafiche = await _trasgressoriService.GetAnagraficheAsync();
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddVerbale(AddVerbaleViewModel addVerbaleViewModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Error while saving entity to database";
                return RedirectToAction("Index");
            }

            var result = await _verbaliService.AddVerbaleAsync(addVerbaleViewModel);

            if (!result)
            {
                TempData["Error"] = "Error while saving entity to database";
            }

            return RedirectToAction("Index");
        }
    }
}

ProgettoBackend-S5-L5/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Polizia Municipale</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/ProgettoBackend_S5_L5.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-primary" asp-area="" asp-controller="Home" asp-action="Index">Polizia Municipale</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Trasgressori" asp-action="Index">Trasgressori</a>
                        </li>                       
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Verbali" asp-action="Index">Verbali</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Polizia Municipale - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>