ProgettoBackend-S5-L5/Controllers/TrasgressoriController.cs
using Microsoft.AspNetCore.Mvc;
using ProgettoBackend_S5_L5.ViewModels;
using ProgettoBackend_S5_L5.Services;

namespace ProgettoBackend_S5_L5.Controllers
{
    public class TrasgressoriController : Controller
    {
        private readonly TrasgressoriService _trasgressoriService;

        public TrasgressoriController(TrasgressoriService trasgressoriService)
        {
            _trasgressoriService = trasgressoriService;
        }
        public async Task<IActionResult> Index()
        {
            var anagrafiche = await _trasgressoriService.GetAnagraficheAsync();

            return View(anagrafiche);
        }

        public IActionResult AddAnagrafiche()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddAnagrafiche(AddAnagraficaViewModel addAnagraficaViewModel)
        {
            if (!ModelState.IsValid)
            {
                TempData["Error"] = "Error while saving entity to database";
                return RedirectToAction("Index");
            }

            var result = await _trasgressoriService.AddAnagraficaAsync(addAnagraficaViewModel);

            if (!result)
            {
                TempData["Error"] = "Error while saving entity to database";
            }

            return RedirectToAction("Index");
        }

    }
}

ProgettoBackend-S5-L5/Views/Trasgressori/AddAnagrafiche.cshtml
@model AddAnagraficaViewModel

@{
	ViewData["Title"] = "Nuova Anagrafica";
}

<h1 class="text-center mt-4 mb-3">Nuovo Trasgressore</h1>
<div class="mb-3">
	<form method="post" asp-controller="Trasgressori" asp-action="AddAnagrafiche">
		<div class="formGroup">
			<label asp-for="Nome" class="form-label"></label>
			<input asp-for="Nome" class="form-control" />
			<span class="text-danger" asp-validation-for="Nome"></span>
		</div>

		<div class="formGroup">
			<label asp-for="Cognome" class="form-label"></label>
			<input type="text" asp-for="Cognome" class="form-control" />
			<span class="text-danger" asp-validation-for="Cognome"></span>
		</div>

		<div class="formGroup">
			<label asp-for="Indirizzo" class="form-label"></label>
			<input asp-for="Indirizzo" class="form-control" />
			<span class="text-danger" asp-validation-for="Indirizzo"></span>
		</div>

		<div class="formGroup">
			<label asp-for="Citta" class="form-label"></label>
			<input asp-for="Citta" class="form-control" />
			<span class="text-danger" asp-validation-for="Citta"></span>
		</div>

		<div class="formGroup">
			<label asp-for="Cap" class="form-label"></label>
			<input asp-for="Cap" class="form-control" />
			<span class="text-danger" asp-validation-for="Cap"></span>
		</div>

		<div class="formGroup">
			<label asp-for="CodFisc" class="form-label"></label>
			<input asp-for="CodFisc" class="form-control" />
			<span class="text-danger" asp-validation-for="CodFisc"></span>
		</div>
		<div class="text-end">
			<div class="text-end">
				<button class="btn btn-success mt-3">Save</button>
			</div>
		</div>
	</form>
</div>

@section Scripts {
	<partial name="_ValidationScriptsPartial" />
}

ProgettoBackend-S5-L5/Views/Trasgressori/Index.cshtml
@model AnagraficaViewModel

@{ViewData["Title"] = "Trasgressori";
}

<h1 class="text-center mt-4 mb-3">Trasgressori</h1>
<div class="text-end mb-3">
	<a asp-controller="Trasgressori" asp-action="AddAnagrafiche" class="btn btn-primary">Nuovo Trasgressore</a>
</div>
<table class="table table-bordered table-hover text-center">
	<thead class="thead-dark ">
		<tr class="text-center centroTab">
			<th>Nome</th>
			<th>Cognome</th>
			<th>Indirizzo</th>
			<th>Città</th>
			<th>Cap</th>
			<th>Codice Fiscale</th>
		</tr>
	</thead>
	<tbody>
		@foreach (var anagrafica in Model.Anagrafiche)
		{
			<tr class="centroTab">
				<td>@anagrafica.Nome</td>
				<td class="">@anagrafica.Cognome</td>
				<td class="">@anagrafica.Indirizzo</td>
				<td class="">@anagrafica.Citta</td>
				<td class="">@anagrafica.Cap</td>
				<td class="">@anagrafica.CodFisc</td>
			</tr>
		}
	</tbody>
</table>